### ISSUE TITLE
request: Cone of Cold

### ISSUE THREAD

**Issue by Orest-Cokan** [RobbieBendick/RangeHelper#1]
**Description:**
I want to request the addition of Cone of Cold to the RangeHelper addon.

**Use case:**
Mages will be less likely to whiff CoC when attempting to farm Pyro blasts.

**Possible Implementation:**
Similar to the existing features such as DB.

**Comment by RobbieBendick** [comment]
good idea. i got you when i have free time.

**Comment by RobbieBendick** [comment]
added CoC to the ability list
